updating some gemfiles and moving the imeplementation of the initial_state to its own module
Getting NGINX to work with UNIX sockets

making SonarCloud happy

Update Dockerfile

Update Dockerfile

Ok, NOW we enable cloud build! 🙃

login to docker firsr

Update action.yml

Update action.yml

ok NOW!!

Update action.yml

Update action.yml

no, NOW we enable cloud build! 🙃

back to local ffmpeg distro?

Changing the Dockerfile to make sure these files are there

try'n'a just get the damn container to run

Update Dockerfile

redo some of these to hopefully get the damn thing to fucking work!

Create poz.world-publish-npm-package.yml

hey there they are!

Update init-nginx

Revert "Thank youpeScript-ify this file"

This reverts commit be01d98283ecc1f6e0671527b44f2bba7ca295d2.

Update Dockerfile

updating some gemfiles and moving the imeplementation of the initial_state to its own module

got these to work

diff --git a/bin/entrypoint b/bin/entrypoint
--- a/bin/entrypoint
+++ b/bin/entrypoint
@@ -1,32 +1,35 @@
-#!/usr/bin/with-contenv bash
+#!/usr/with-contenv bash
 # shellcheck shell=bash
-
+echo "Entering entrypoint."
 set -e
-export RAILS_ENV=production
-export PATH="/opt/mastodon/bin:/bin:/usr/bin:/usr/sbin:/usr/local/bin:${PATH}"
-export PROGRAM="$1"
 
-/opt/mastodon/bin/start-sshd
-/opt/mastodon/bin/start-nginx
+/opt/mastodon/bin/start-sshd;
 
-/opt/mastodon/bin/show-branding
+/opt/mastodon/bin/show-branding;
 
 if [[ $PROGRAM == "mastodon" ]]; then
-    /opt/mastodon/bin/show-mastodon-branding
-    /opt/mastodon/bin/start-mastodon 
+    /opt/mastodon/bin/show-mastodon-branding;
+    /opt/mastodon/bin/start-mastodon;
 elif [[ $PROGRAM == "sidekiq" ]]; then
-    /opt/mastodon/bin/show-sidekiq-branding
-    /opt/mastodon/bin/start-sidekiq 
+    /opt/mastodon/bin/show-sidekiq-branding;
+    /opt/mastodon/bin/start-sidekiq;
 elif [[ $PROGRAM == "streaming" ]]; then
-    /opt/mastodon/bin/show-streaming-branding
-    /opt/mastodon/bin/start-streaming 
+    /opt/mastodon/bin/show-streaming-branding;
+    /opt/mastodon/bin/start-streaming;
 elif [[ $PROGRAM == "all" ]]; then
-    /opt/mastodon/bin/show-mastodon-branding
-    /opt/mastodon/bin/start-mastodon 
-    /opt/mastodon/bin/show-sidekiq-branding
-    /opt/mastodon/bin/start-sidekiq 
-    /opt/mastodon/bin/show-mastodon-branding
-    /opt/mastodon/bin/start-streaming 
+    /opt/mastodon/bin/show-mastodon-branding;
+    /opt/mastodon/bin/start-mastodon;
+    /opt/mastodon/bin/show-sidekiq-branding;
+    /opt/mastodon/bin/start-sidekiq;
+    /opt/mastodon/bin/show-mastodon-branding;
+    /opt/mastodon/bin/start-streaming;
 else
-    /bin/echo "Program '${PROGRAM}' was not found and could not be started.";
+    echo "Program '${PROGRAM}' was not found and could not be started.";
+    exit 1;
 fi
+
+/opt/mastodon/bin/start-nginx;
+
+/opt/mastodon/bin/sleep-forever;
+
+echo "Exiting entrypoint."
